In [68]:
import numpy as np

# help(np)
arr = np.array([[10,20,30,40,50],
                 [20,40,60,40,30],
                 [20,40,60,40,30]])
# arr.ndim
# arr.shape
# arr.size
# arr.shape

brr = np.array([i for i in range(1,21)],ndmin=7)
brr.ndim

# help(np.ndim)
l = [i for i in range(1,11)]
m = [i for i in range(1,11)]
arr = np.array([l,l])
brr = np.array(m)
# print(l)
# print(m)
# brr * arr
# print(arr)
# arr[0:5:2]
# arr[-5:-1]
# arr.size

a = np.array([10.2,20.4,30.5])

# help(np.array)
b = a.astype(str)

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 100
x

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 100
arr

array([100,   2,   3,   4,   5])

In [70]:
arr = np.array([1, 2, 3, 4], ndmin=2)
arr

array([[1, 2, 3, 4]])

In [75]:
arr = np.array([i for i in range(1,13)])

a = arr.reshape(3,4)

s = a.reshape(-1)
s

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [78]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for i in np.nditer(arr):
    print(i)



1
2
3
4
5
6
7
8


In [79]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))
arr

array([1, 2, 3, 4, 5, 6])

In [83]:
idn = np.eye(4,dtype="int")
idn

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [82]:
ones = np.ones((2,3),dtype="int")
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [84]:
zeros = np.zeros((5,5),dtype="int")
zeros

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [91]:
wish = np.full((3,3),[3,4,5])
wish

array([[3, 4, 5],
       [3, 4, 5],
       [3, 4, 5]])

In [92]:
arr = np.array([[10,20,30],[100,200,300]])


array([[ 10,  20,  30],
       [100, 200, 300]])